<?php

namespace Omnipay\BillPay\Message\RequestData;

use Omnipay\Common\Exception\InvalidRequestException;
use Omnipay\Common\Message\AbstractRequest;
use SimpleXMLElement;

/**
 * Class CancelTrait.
 *
 * @author    Andreas Lange <andreas.lange@quillo.de>
 * @copyright 2016, Quillo GmbH
 * @license   MIT
 */
trait CancelTrait
{
    /**
     * Validates and returns the formated amount.
     *
     * @throws InvalidRequestException on any validation failure.
     *
     * @return string The amount formatted to the correct number of decimal places for the selected currency.
     */
    abstract public function getAmount();

    /**
     * Get the payment currency code.
     *
     * @return string
     */
    abstract public function getCurrency();

    /**
     * Get the transaction ID.
     *
     * The transaction ID is the identifier generated by the merchant website.
     *
     * @return string
     */
    abstract public function getTransactionId();

    /**
     * Appends the rate request node to the SimpleXMLElement.
     *
     * @param SimpleXMLElement $data
     *
     * @throws InvalidRequestException
     */
    protected function appendCancel(SimpleXMLElement $data)
    {
        $data->addChild('cancel_params');
        $data->cancel_params[0]['carttotalgross'] = round(bcmul($this->getAmount(), 100, 8));
        $data->cancel_params[0]['currency'] = $this->getCurrency();
        $data->cancel_params[0]['reference'] = $this->getTransactionId();
    }

    /**
     * Get a single parameter.
     *
     * @param string $key The parameter key
     *
     * @return mixed
     */
    abstract protected function getParameter($key);

    /**
     * Set a single parameter.
     *
     * @param string $key   The parameter key
     * @param mixed  $value The value to set
     *
     * @return AbstractRequest Provides a fluent interface
     */
    abstract protected function setParameter($key, $value);
}
